# Generated by Django 5.2.4 on 2025-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=225)),
                ('confirmpassword', models.CharField(max_length=225)),
            ],
        ),
    ]
