# Generated by Django 5.2.4 on 2025-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_remove_signup_confirmpassword_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('productprice', models.IntegerField()),
                ('productdescription', models.TextField()),
                ('productcategory', models.CharField(max_length=255)),
                ('productquantity', models.IntegerField()),
            ],
        ),
    ]
