# Generated by Django 5.2.4 on 2025-08-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_category_coupon_customer_cart_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
