[phases.setup]
nixPkgs = ["gcc", "libc6-dev", "curl", "pango", "cairo", "gobject-introspection", "libffi"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.install]
cmds = [
    "pip install --upgrade pip", 
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps chromium"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
